contactEmail: takafumi.hori.official@gmail.com
instagram: https://www.instagram.com/detourne.official/
youtube: https://www.youtube.com/@detourne.official
x: https://x.com/detourne_ofcl
amazonTag: ''
